#pragma once

#include <cstddef>
#include <filesystem>
#include <string>
#include <string_view>
#include <unordered_set>
#include <vector>

/**
 * @file filter_core.h
 * @brief Turns a raw text excerpt into the short list of words worth explaining.
 *
 * The pipeline is deliberately dependency-free: no I/O and no Qt, so it can be unit
 * tested offline. Frequency ranks come from a static word list, and the caller injects
 * the known set and the difficulty cut-off.
 */

namespace lens::core {

/**
 * @brief Load the static word list into process-wide read-only state.
 *
 * @param path Word list file: one word per line, ordered by descending frequency.
 * @throws std::runtime_error If the file cannot be opened or contains no entries.
 *
 * @note Must run before lemmatize() or filterWords(). Those two throw std::logic_error
 *       rather than returning nothing, because calling them first is an initialisation
 *       order bug -- silently dropping every candidate would hide it.
 */
void loadWordlist(const std::filesystem::path& path);

/**
 * @brief Load the irregular inflection table into process-wide read-only state.
 *
 * @param path Tab-separated file of `form<TAB>base`, one pair per line; `#` starts a
 *             comment. `data/irregulars.tsv` is generated by
 *             `scripts/gen_irregulars.py` from the WordNet inflection exception lists.
 * @throws std::runtime_error If the file cannot be opened, holds no pairs, or carries a
 *         line that is not a comment and not a pair.
 *
 * @note Must run before lemmatize() or filterWords(), alongside loadWordlist(). The two
 *       answer different questions -- the word list says whether a word is real, this
 *       says what its base form is -- so neither can stand in for the other.
 */
void loadIrregulars(const std::filesystem::path& path);

/**
 * @brief Reduce a token to its dictionary form, so "running" and "ran" both become "run".
 *
 * Irregular forms are decided by the loaded table. Everything else is reduced by suffix
 * rules cross-checked against the word list.
 *
 * @param token Word to reduce, case-insensitive.
 * @return The lemma. The known set, the explanation cache, and word list lookups are
 *         all keyed by lemma rather than by the form as written.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 */
std::string lemmatize(std::string_view token);

/// @brief A word worth explaining, in both the form seen and its dictionary form.
struct Candidate {
    std::string surface; ///< The form as written, lower-cased (e.g. "running").
    std::string lemma;   ///< The dictionary form (e.g. "run").
};

/**
 * @brief Filter an excerpt down to the words the reader probably does not know.
 *
 * Pure pipeline with no I/O; the known set and the frequency cut-off are injected so the
 * module stays dependency-free and testable. Stages, in order: tokenise and hard-filter
 * -> skip all-caps -> lemmatise -> whitelist against the word list -> difficulty cut-off
 * -> skip known lemmas.
 *
 * @param text         Raw excerpt, typically pasted from the clipboard.
 * @param knownLemmas  Lemmas the reader has already marked as known.
 * @param minFreqRank  Difficulty cut-off: words at or above this rank count as mastered.
 *                     The level-to-rank mapping is not settled yet; see TODO.md.
 * @return Candidates in order of first appearance, de-duplicated by lemma.
 *         An empty vector means nothing needs explaining.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 */
std::vector<Candidate> filterWords(
    std::string_view text,
    const std::unordered_set<std::string>& knownLemmas,
    std::size_t minFreqRank);

/// @brief What a finished selection turned out to be, which decides the channel it takes.
///
/// Phase 2's entity channel joins this enumeration; the sentence channel already has its
/// value. Nothing here is decided by the reader: translate and explain are two ways into
/// the same decision, so it is settled when the selection is analysed, before any press
/// (UI.md section 4.9).
enum class SelectionKind {
    Word,     ///< At least one candidate came back; the word channel has something to send.
    Sentence, ///< No candidate. Phase 2's sentence and entity channels own this case.
};

/// @brief A selection, classified: what it is, and the words it would send.
struct Selection {
    SelectionKind kind = SelectionKind::Sentence;
    std::vector<Candidate> candidates; ///< Empty unless kind is Word.
};

/**
 * @brief Decide what a selection is, and produce the words a request would carry.
 *
 * One place decides this, and the surfaces only route on the answer -- so picking translate
 * over explain cannot change the channel, and phase 2's entity channel is a branch here
 * rather than a second opinion somewhere else.
 *
 * @param text         Raw excerpt, exactly as filterWords takes it.
 * @param knownLemmas  Lemmas the reader has already marked as known.
 * @param minFreqRank  Difficulty cut-off.
 * @return The kind, and the candidates when there are any.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 *
 * @note Sentence is the absence of a candidate, not a judgement about grammar: a lone word
 *       the reader already knows lands there too. That is the honest answer -- there is
 *       nothing left in the selection to explain.
 */
Selection classifySelection(
    std::string_view text,
    const std::unordered_set<std::string>& knownLemmas,
    std::size_t minFreqRank);

}
