#pragma once

#include <cstddef>
#include <filesystem>
#include <string>
#include <string_view>
#include <unordered_set>
#include <vector>

/**
 * @file filter_core.h
 * @brief Turns a raw text excerpt into the short list of words worth explaining.
 *
 * The pipeline is deliberately dependency-free: no I/O and no Qt, so it can be unit
 * tested offline. Frequency ranks come from a static word list, and the caller injects
 * the known set and the difficulty cut-off.
 */

namespace lens::core {

/**
 * @brief Load the static word list into process-wide read-only state.
 *
 * @param path Word list file: one word per line, ordered by descending frequency.
 * @throws std::runtime_error If the file cannot be opened or contains no entries.
 *
 * @note Must run before lemmatize() or filterWords(). Those two throw std::logic_error
 *       rather than returning nothing, because calling them first is an initialisation
 *       order bug -- silently dropping every candidate would hide it.
 */
void loadWordlist(const std::filesystem::path& path);

/**
 * @brief Load the irregular inflection table into process-wide read-only state.
 *
 * @param path Tab-separated file of `form<TAB>base`, one pair per line; `#` starts a
 *             comment. `data/irregulars.tsv` is generated by
 *             `scripts/gen_irregulars.py` from the WordNet inflection exception lists.
 * @throws std::runtime_error If the file cannot be opened, holds no pairs, or carries a
 *         line that is not a comment and not a pair.
 *
 * @note Must run before lemmatize() or filterWords(), alongside loadWordlist(). The two
 *       answer different questions -- the word list says whether a word is real, this
 *       says what its base form is -- so neither can stand in for the other.
 */
void loadIrregulars(const std::filesystem::path& path);

/**
 * @brief Reduce a token to its dictionary form, so "running" and "ran" both become "run".
 *
 * Irregular forms are decided by the loaded table. Everything else is reduced by suffix
 * rules cross-checked against the word list.
 *
 * @param token Word to reduce, case-insensitive.
 * @return The lemma. The known set, the explanation cache, and word list lookups are
 *         all keyed by lemma rather than by the form as written.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 */
std::string lemmatize(std::string_view token);

/// @brief Where a candidate stands with the reader. The module records it; the caller acts.
///
/// Known and Mastered are kept apart because they are told apart: one is the reader's own
/// mark, the other the level's frequency band. Either way the word stays a candidate, since
/// a selection the reader made by hand is a request to explain it whatever they once marked
/// (TODO.md item 0). Phase 2's automatic scanning is the caller that will want to skip them.
enum class CandidateState {
    New,      ///< Neither marked nor inside the level's band.
    Known,    ///< The reader marked it as known.
    Mastered, ///< Inside the level's frequency band.
};

/// @brief A word worth explaining, in both the form seen and its dictionary form.
struct Candidate {
    std::string surface;                        ///< The form as written, lower-cased (e.g. "running").
    std::string lemma;                          ///< The dictionary form (e.g. "run").
    CandidateState state = CandidateState::New; ///< What the reader has already said about it.
};

/**
 * @brief Filter an excerpt down to the words it is made of.
 *
 * Pure pipeline with no I/O; the known set and the frequency cut-off are injected so the
 * module stays dependency-free and testable. Stages, in order: tokenise and hard-filter
 * -> skip all-caps -> lemmatise -> whitelist against the word list -> de-duplicate by lemma
 * -> record each survivor's state.
 *
 * The known set and the frequency cut-off annotate a candidate; they never remove one. What
 * removes a word is the hard filter, and that is the whole test for whether it is a word at
 * all: length, case, a vowel, glued punctuation, and membership of the static word list.
 *
 * One explicit exception: when the whole selection is a single letters-only token of two or
 * more letters, in any case ("QML", "qml", "NASA", "ok", "am"), it is a word the reader picked
 * by hand, so it becomes a candidate -- the lower-cased token itself -- whatever those gates
 * say. The static list holds few acronyms and identifiers, and qml has no vowel, so without
 * this a selected term would fall through to the sentence channel. A digit or interior
 * punctuation disqualifies it (MP3, contractions stay out), and in continuous prose the gates
 * still apply: only a selection that is exactly this one token qualifies.
 *
 * @param text         Raw excerpt, typically pasted from the clipboard.
 * @param knownLemmas  Lemmas the reader has already marked as known; a hit is recorded as
 *                     CandidateState::Known.
 * @param minFreqRank  Difficulty cut-off: a lemma ranked at or above it is recorded as
 *                     CandidateState::Mastered. The level-to-rank mapping is not settled
 *                     yet; see TODO.md.
 * @return Every surviving word, in order of first appearance, de-duplicated by lemma.
 *         An empty vector means the excerpt holds no word from the static list at all.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 */
std::vector<Candidate> filterWords(
    std::string_view text,
    const std::unordered_set<std::string>& knownLemmas,
    std::size_t minFreqRank);

/// @brief What a finished selection turned out to be, which decides the channel it takes.
///
/// Nothing here is decided by the reader: translate and explain are two ways into the same
/// decision, so it is settled when the selection is analysed, before any press (UI.md section
/// 4.9). Entity detection is deliberately conservative: only a complete phrase with at least
/// two adjacent Title Case tokens qualifies, never a single capitalized token.
enum class SelectionKind {
    Word,     ///< The whole selection is one letters-only token: a lookup, not a translation.
    Entity,   ///< A complete multi-token Title Case phrase was selected.
    Sentence, ///< More than one token; the sentence channel translates or explains it whole.
};

/// @brief A selection, classified: what it is, and the candidates it carries.
struct Selection {
    SelectionKind kind = SelectionKind::Sentence;
    std::vector<Candidate> candidates; ///< Empty unless kind is Word.
};

/**
 * @brief Decide what a selection is, and produce the candidates a request would choose from.
 *
 * One place decides this, and the surfaces only route on the answer -- so picking translate
 * over explain cannot change the channel, and phase 2's entity channel is a branch here
 * rather than a second opinion somewhere else.
 *
 * @param text         Raw excerpt, exactly as filterWords takes it.
 * @param knownLemmas  Lemmas the reader has already marked as known.
 * @param minFreqRank  Difficulty cut-off.
 * @return The kind, and the candidates when there are any.
 * @throws std::logic_error If loadWordlist() or loadIrregulars() has not run yet.
 *
 * @note The channel is the shape of the selection, not whether it holds a word worth showing: a
 *       lone letters-only token (a word, an acronym, a word the reader marked known) is Word,
 *       and anything with more than one token -- a phrase or a sentence -- is Sentence, whatever
 *       its words are. Entity takes the multi-token Title Case phrases first. Which candidate a
 *       Word carries is the caller's decision, taken from each candidate's state.
 */
Selection classifySelection(
    std::string_view text,
    const std::unordered_set<std::string>& knownLemmas,
    std::size_t minFreqRank);

}
