#!/usr/bin/env python3
"""Regenerate data/irregulars.tsv from WordNet's inflection exception lists.

WordNet ships four `.exc` files listing the inflected forms whose base form its own
suffix rules cannot derive (went -> go, mice -> mouse, abetted -> abet). They are the
standard reference for English irregular inflection, so the runtime table is generated
from them rather than hand-written.

    python scripts/gen_irregulars.py

Requires nltk with the wordnet corpus downloaded (`nltk.download('wordnet')`). If
wordnet is stored as a zip it is read through zipfile, so nothing has to be unpacked.

The curated block at the bottom covers forms the source is missing; WordNet treats a few
plurals as lemmas in their own right and lists no mapping for them. Keep that block small
and comment each entry with why it is there.
"""

import glob
import os
import sys
import zipfile

EXC_FILES = ("verb.exc", "noun.exc", "adj.exc", "adv.exc")

# WordNet lists no mapping for these; both read as their own lemma to its lemmatizer.
# They are common enough that leaving them out would show as an unexplained gap.
CURATED = {
    "women": "woman",
    "people": "person",
}

OUTPUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "data", "irregulars.tsv")


def find_wordnet_records():
    """Return the path of the WordNet corpus, zip or directory."""
    roots = [p for p in (os.environ.get("NLTK_DATA"),) if p]
    roots += [os.path.expanduser("~/AppData/Roaming/nltk_data"),
              os.path.expanduser("~/nltk_data"),
              "/usr/share/nltk_data", "/usr/local/share/nltk_data"]
    for root in roots:
        hits = sorted(glob.glob(os.path.join(root, "**", "wordnet"), recursive=True))
        hits += sorted(glob.glob(os.path.join(root, "**", "wordnet.zip"), recursive=True))
        if hits:
            return hits[0]
    raise SystemExit("wordnet corpus not found; run nltk.download('wordnet') first")


def read_exc(path):
    """Yield (form, lemma) for every row of every exception file."""
    if path.endswith(".zip"):
        with zipfile.ZipFile(path) as archive:
            names = [n for n in archive.namelist()
                     if os.path.basename(n) in EXC_FILES]
            for name in names:
                for line in archive.read(name).decode("utf-8").splitlines():
                    if line.split():
                        yield line.split()[:2]
    else:
        for name in EXC_FILES:
            full = os.path.join(path, name)
            if not os.path.exists(full):
                continue
            with open(full, encoding="utf-8") as handle:
                for line in handle:
                    if line.split():
                        yield line.split()[:2]


def main():
    records = find_wordnet_records()
    pairs = set()
    identity = 0
    for form, lemma in read_exc(records):
        form, lemma = form.lower(), lemma.lower()
        if form == lemma:
            identity += 1          # forms that are their own base; nothing to map
            continue
        pairs.add((form, lemma))

    generated = len(pairs)
    for form, lemma in CURATED.items():
        pairs.add((form, lemma))

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as out:
        out.write("# Inflected form -> base form, tab separated, one pair per line.\n")
        out.write("# Generated by scripts/gen_irregulars.py from the WordNet inflection\n")
        out.write("# exception lists (verb.exc, noun.exc, adj.exc, adv.exc).\n")
        out.write(f"# {generated} generated pair(s) plus {len(CURATED)} curated; "
                  f"{identity} identity row(s) dropped.\n")
        out.write("# Loaded by lens::core::loadIrregulars().\n")
        for form, lemma in sorted(pairs):
            out.write(f"{form}\t{lemma}\n")

    print(f"source: {records}")
    print(f"wrote {len(pairs)} pairs to {OUTPUT} ({identity} identity rows dropped)")


if __name__ == "__main__":
    sys.exit(main())
